Autoconf update.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3671,18 +3671,18 @@ esac
 
 	{ echo "$as_me:$LINENO: checking for C99" >&5
 echo $ECHO_N "checking for C99... $ECHO_C" >&6; }
-	if test x$ac_cv_prog_cc_c99 != xno ; then
+	if test "x$ac_cv_prog_cc_c99" != "xno" ; then
 		{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 
-  if test x$ac_cv_prog_cc_c99 = xyes ; then
+  if test "xyes" = "xyes" ; then
 
 cat >>confdefs.h <<_ACEOF
-#define HAVE_C99
+#define HAVE_C99 1
 _ACEOF
 
   fi
-   if test x$ac_cv_prog_cc_c99 = xyes; then
+   if test "xyes" = "xyes"; then
   HAVE_C99_TRUE=
   HAVE_C99_FALSE='#'
 else
@@ -3690,7 +3690,7 @@ else
   HAVE_C99_FALSE=
 fi
 
-  HAVE_C99=$ac_cv_prog_cc_c99
+  HAVE_C99=yes
 
 
 	else
@@ -5196,14 +5196,14 @@ fi
 	fi
 
 
-  if test x$debug = xyes ; then
+  if test "x$debug" = "xyes" ; then
 
 cat >>confdefs.h <<_ACEOF
-#define TRIPCRUNCH_DEBUG
+#define TRIPCRUNCH_DEBUG 1
 _ACEOF
 
   fi
-   if test x$debug = xyes; then
+   if test "x$debug" = "xyes"; then
   TRIPCRUNCH_DEBUG_TRUE=
   TRIPCRUNCH_DEBUG_FALSE='#'
 else
@@ -5934,6 +5934,622 @@ echo $ECHO_N "checking if $CXX accepts -ffast-math... $ECHO_C" >&6; }
 		fi
 	else
 		CXXFLAGS="-ffast-math"
+	fi
+
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  flag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	flag=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		if test x$flag = xno ; then
+			CXXFLAGS="$CXXFLAGS_save"
+		fi
+		{ echo "$as_me:$LINENO: result: $flag" >&5
+echo "${ECHO_T}$flag" >&6; }
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	fi
+
+
+
+
+	if test "x$CC" != x ; then
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+		{ echo "$as_me:$LINENO: checking if $CC accepts -fgcse-sm" >&5
+echo $ECHO_N "checking if $CC accepts -fgcse-sm... $ECHO_C" >&6; }
+		CFLAGS_save=$CFLAGS
+
+	CFLAGS_addsave=$CFLAGS
+	if test "x$CFLAGS_addsave" != "x" ; then
+		flag=`echo "-fgcse-sm" | sed 's/-/\\\-/g'`
+		if test -z "`echo \"${CFLAGS}\" | grep \"${flag}\"`" ; then
+			CFLAGS="$CFLAGS_addsave -fgcse-sm"
+		fi
+	else
+		CFLAGS="-fgcse-sm"
+	fi
+
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  flag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	flag=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		if test x$flag = xno ; then
+			CFLAGS="$CFLAGS_save"
+		fi
+		{ echo "$as_me:$LINENO: result: $flag" >&5
+echo "${ECHO_T}$flag" >&6; }
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	fi
+
+
+	if test "x$CXX" != x ; then
+		ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+		{ echo "$as_me:$LINENO: checking if $CXX accepts -fgcse-sm" >&5
+echo $ECHO_N "checking if $CXX accepts -fgcse-sm... $ECHO_C" >&6; }
+		CXXFLAGS_save=$CXXFLAGS
+
+	CXXFLAGS_addsave=$CXXFLAGS
+	if test "x$CXXFLAGS_addsave" != "x" ; then
+		flag=`echo "-fgcse-sm" | sed 's/-/\\\-/g'`
+		if test -z "`echo \"${CXXFLAGS}\" | grep \"${flag}\"`" ; then
+			CXXFLAGS="$CXXFLAGS_addsave -fgcse-sm"
+		fi
+	else
+		CXXFLAGS="-fgcse-sm"
+	fi
+
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  flag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	flag=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		if test x$flag = xno ; then
+			CXXFLAGS="$CXXFLAGS_save"
+		fi
+		{ echo "$as_me:$LINENO: result: $flag" >&5
+echo "${ECHO_T}$flag" >&6; }
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	fi
+
+
+
+
+	if test "x$CC" != x ; then
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+		{ echo "$as_me:$LINENO: checking if $CC accepts -fgcse-las" >&5
+echo $ECHO_N "checking if $CC accepts -fgcse-las... $ECHO_C" >&6; }
+		CFLAGS_save=$CFLAGS
+
+	CFLAGS_addsave=$CFLAGS
+	if test "x$CFLAGS_addsave" != "x" ; then
+		flag=`echo "-fgcse-las" | sed 's/-/\\\-/g'`
+		if test -z "`echo \"${CFLAGS}\" | grep \"${flag}\"`" ; then
+			CFLAGS="$CFLAGS_addsave -fgcse-las"
+		fi
+	else
+		CFLAGS="-fgcse-las"
+	fi
+
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  flag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	flag=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		if test x$flag = xno ; then
+			CFLAGS="$CFLAGS_save"
+		fi
+		{ echo "$as_me:$LINENO: result: $flag" >&5
+echo "${ECHO_T}$flag" >&6; }
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	fi
+
+
+	if test "x$CXX" != x ; then
+		ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+		{ echo "$as_me:$LINENO: checking if $CXX accepts -fgcse-las" >&5
+echo $ECHO_N "checking if $CXX accepts -fgcse-las... $ECHO_C" >&6; }
+		CXXFLAGS_save=$CXXFLAGS
+
+	CXXFLAGS_addsave=$CXXFLAGS
+	if test "x$CXXFLAGS_addsave" != "x" ; then
+		flag=`echo "-fgcse-las" | sed 's/-/\\\-/g'`
+		if test -z "`echo \"${CXXFLAGS}\" | grep \"${flag}\"`" ; then
+			CXXFLAGS="$CXXFLAGS_addsave -fgcse-las"
+		fi
+	else
+		CXXFLAGS="-fgcse-las"
+	fi
+
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  flag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	flag=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		if test x$flag = xno ; then
+			CXXFLAGS="$CXXFLAGS_save"
+		fi
+		{ echo "$as_me:$LINENO: result: $flag" >&5
+echo "${ECHO_T}$flag" >&6; }
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	fi
+
+
+
+
+	if test "x$CC" != x ; then
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+		{ echo "$as_me:$LINENO: checking if $CC accepts -fgcse-after-reload" >&5
+echo $ECHO_N "checking if $CC accepts -fgcse-after-reload... $ECHO_C" >&6; }
+		CFLAGS_save=$CFLAGS
+
+	CFLAGS_addsave=$CFLAGS
+	if test "x$CFLAGS_addsave" != "x" ; then
+		flag=`echo "-fgcse-after-reload" | sed 's/-/\\\-/g'`
+		if test -z "`echo \"${CFLAGS}\" | grep \"${flag}\"`" ; then
+			CFLAGS="$CFLAGS_addsave -fgcse-after-reload"
+		fi
+	else
+		CFLAGS="-fgcse-after-reload"
+	fi
+
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  flag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	flag=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		if test x$flag = xno ; then
+			CFLAGS="$CFLAGS_save"
+		fi
+		{ echo "$as_me:$LINENO: result: $flag" >&5
+echo "${ECHO_T}$flag" >&6; }
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	fi
+
+
+	if test "x$CXX" != x ; then
+		ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+		{ echo "$as_me:$LINENO: checking if $CXX accepts -fgcse-after-reload" >&5
+echo $ECHO_N "checking if $CXX accepts -fgcse-after-reload... $ECHO_C" >&6; }
+		CXXFLAGS_save=$CXXFLAGS
+
+	CXXFLAGS_addsave=$CXXFLAGS
+	if test "x$CXXFLAGS_addsave" != "x" ; then
+		flag=`echo "-fgcse-after-reload" | sed 's/-/\\\-/g'`
+		if test -z "`echo \"${CXXFLAGS}\" | grep \"${flag}\"`" ; then
+			CXXFLAGS="$CXXFLAGS_addsave -fgcse-after-reload"
+		fi
+	else
+		CXXFLAGS="-fgcse-after-reload"
+	fi
+
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  flag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	flag=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		if test x$flag = xno ; then
+			CXXFLAGS="$CXXFLAGS_save"
+		fi
+		{ echo "$as_me:$LINENO: result: $flag" >&5
+echo "${ECHO_T}$flag" >&6; }
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	fi
+
+
+
+
+	if test "x$CC" != x ; then
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+		{ echo "$as_me:$LINENO: checking if $CC accepts -fsee" >&5
+echo $ECHO_N "checking if $CC accepts -fsee... $ECHO_C" >&6; }
+		CFLAGS_save=$CFLAGS
+
+	CFLAGS_addsave=$CFLAGS
+	if test "x$CFLAGS_addsave" != "x" ; then
+		flag=`echo "-fsee" | sed 's/-/\\\-/g'`
+		if test -z "`echo \"${CFLAGS}\" | grep \"${flag}\"`" ; then
+			CFLAGS="$CFLAGS_addsave -fsee"
+		fi
+	else
+		CFLAGS="-fsee"
+	fi
+
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  flag=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	flag=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		if test x$flag = xno ; then
+			CFLAGS="$CFLAGS_save"
+		fi
+		{ echo "$as_me:$LINENO: result: $flag" >&5
+echo "${ECHO_T}$flag" >&6; }
+		ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	fi
+
+
+	if test "x$CXX" != x ; then
+		ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+		{ echo "$as_me:$LINENO: checking if $CXX accepts -fsee" >&5
+echo $ECHO_N "checking if $CXX accepts -fsee... $ECHO_C" >&6; }
+		CXXFLAGS_save=$CXXFLAGS
+
+	CXXFLAGS_addsave=$CXXFLAGS
+	if test "x$CXXFLAGS_addsave" != "x" ; then
+		flag=`echo "-fsee" | sed 's/-/\\\-/g'`
+		if test -z "`echo \"${CXXFLAGS}\" | grep \"${flag}\"`" ; then
+			CXXFLAGS="$CXXFLAGS_addsave -fsee"
+		fi
+	else
+		CXXFLAGS="-fsee"
 	fi
 
 		cat >conftest.$ac_ext <<_ACEOF
